# Generated by Django 5.0.7 on 2024-08-07 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=255)),
                ('bug_date', models.DateField()),
                ('bug_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('bug_severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('normal', 'Normal'), ('minor', 'Minor'), ('trivial', 'Trivial'), ('enhancement', 'Enhancements/Feature Requests')], max_length=15)),
                ('bug_type', models.CharField(choices=[('error', 'Error'), ('mistake', 'Mistake'), ('bug', 'Bug'), ('issue', 'Issue'), ('fault', 'Fault'), ('defect', 'Defect')], max_length=10)),
                ('description', models.TextField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_progress', 'In Progress')], max_length=15)),
                ('is_current_project', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bugs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bugs', to='department.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bugs', to='project.project')),
            ],
        ),
    ]
