# Generated by Django 5.0.7 on 2024-08-07 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/', verbose_name='Bug_Image'),
            preserve_default=False,
        ),
    ]
