# Generated by Django 5.0.7 on 2024-08-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='bug_report_date',
            new_name='report_date',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='url_of_the_bug',
        ),
        migrations.AddField(
            model_name='bug',
            name='url_bug',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Normal', 'Normal'), ('Minor', 'Minor'), ('Trivial', 'Trivial'), ('Enhancements/Feature Requests', 'Enhancements/Feature Requests')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('Error', 'Error'), ('Mistake', 'Mistake'), ('Bug', 'Bug'), ('Issue', 'Issue'), ('Fault', 'Fault'), ('Defect', 'Defect'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bugs/images/'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('In Progress', 'In Progress')], default='Open', max_length=20),
        ),
    ]
