# Generated by Django 5.0.7 on 2024-08-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_rename_bug_report_date_bug_report_date_and_more'),
        ('department', '0002_alter_department_user'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Normal', 'Normal'), ('Minor', 'Minor'), ('Trivial', 'Trivial'), ('Enhancements/Feature Requests', 'Enhancements/Feature Requests')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bug',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='department.department'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='project.project'),
        ),
    ]
