# Generated by Django 5.0.7 on 2024-08-08 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('team_lead', 'Team Lead'), ('developer', 'Developer'), ('customer', 'Customer'), ('tester', 'Tester'), ('manager', 'Manager')], max_length=20)),
                ('dept', models.CharField(choices=[('python', 'Python'), ('php', 'PHP'), ('java', 'Java'), ('angular', 'Angular'), ('mobile_app', 'Mobile App'), ('devops', 'DevOps'), ('tester', 'Tester'), ('management', 'Management'), ('client', 'Client')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
