# Generated by Django 5.0.7 on 2024-08-07 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Customer', 'Customer'), ('DevOps', 'DevOps'), ('Java', 'Java'), ('Management', 'Management'), ('PHP', 'PHP'), ('Python', 'Python')], max_length=50)),
                ('role', models.CharField(choices=[('Project Lead', 'Project Lead'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('Manager', 'Manager'), ('Client', 'Client')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
